{% set version = "3.1.0rc3" %}

package:
  name: azure-mgmt-compute
  version: {{ version }}

source:
  fn: azure-mgmt-compute-{{ version }}.zip
  url: https://pypi.io/packages/source/a/azure-mgmt-compute/azure-mgmt-compute-{{ version }}.zip
  md5: 6a6ab8b429fa8bae8425a4b702c252fdcc28339b3c48d737a9bce566d76e151a
  
build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    - python
    - setuptools
    - azure-mgmt-common
  run:
    - python
    - azure-mgmt-common

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.compute
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: Apache-2.0
  summary: 'Microsoft Azure Client Libraries for Python'

extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - Maxyme
