{% set name = "azure-mgmt-compute" %}
{% set version = "3.1.0rc3" %}
{% set sha256 = "6a6ab8b429fa8bae8425a4b702c252fdcc28339b3c48d737a9bce566d76e151a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - azure-mgmt-common

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.compute
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: Apache-2.0
  summary: 'Microsoft Azure Client Libraries for Python'

extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - Maxyme
