travis:
  secure:
    BINSTAR_TOKEN: LrQpxz+8VUI2tWqaR6NhQowUCGFywrhM3vu/OETdaLgYVXigMYAX3/uZjNh66w5J/nhVO5WJiFVVxdxmfjhdIXoslhnH0r+qaqd/ZQj2auQmotjP6L0En06tCtitQ+m4odRVYRQDG51ryd9EVOXwTrg7xrY+XoL5JEQWPoKCcz//+KuHLaE34Lzkzmyf1M7KVM6AZk+hnn3oI/ikdnzd0GbIB4M5V6PFnjtl8qFXhtNI07IBNPSph/83mo37bsvpZPadNIfZAUE1fsbBJfY30o/itlpjTyrtG1MTfsDjdaTNU14Tux0Trw4ciS4PVtMtkmIBO3ijF4shnwrYMvBflgTlC0iIlglgl+aTx0XgSRYqjeclcZdUGuYAl72fsaYvEeBB2guGTdSeE7BNth5kgjJWpKOt8bxtWKgroteutB9Gw0B7fgfy8DAyKTSb6btYItYP0zjNMeEQaHYJ+uI5pBMJ4Pm0MonLnoUTjnQmQ0Vakp/F2dYi8w1WIvW/4Gt8lQ/xasFK1K5AbM9H0sUuC/A7wwpolV9lu4SnBWKc9U6fjA1s46rXTURlDj+fAyxxtVtX6XWPE1tkwDUjbwfHx2ZrhKoIY9fObz7DPW510TK6CdvUhq+Gfnanzu56Nn5mrOZqjJPKd6m8HTzbYntwbw1hBx3EWPRdddXObVYUyog=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
